const fs = require("fs")
const path = require("path")
const common = require("../../utils/common.js")
const request = require("../../utils/request.js")
const response = require("../../utils/response.js")
const CaptureUtils = require("../../libs/du/utils.js")
const CaptureDetail = require("../../libs/du/captureDetail.js")